import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsUUID } from 'class-validator';

// ─── Accept Invite ────────────────────────────────────────────────────────────

export class AcceptInviteDto {
  @ApiProperty({
    description: 'Invite token generated by fleet manager',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @IsString()
  @IsNotEmpty()
  @IsUUID('4')
  token: string;
}

export class AcceptInviteResponseDto {
  @ApiProperty()
  driver_id: string;
}

// ─── Driver Profile ───────────────────────────────────────────────────────────

export class DriverProfileResponse {
  @ApiProperty() id: string;
  @ApiProperty() first_name: string;
  @ApiProperty() last_name: string;
  @ApiPropertyOptional() email: string | null;
  @ApiPropertyOptional() mobile: string | null;
  @ApiPropertyOptional() dob: Date | null;
  @ApiPropertyOptional() license_number: string | null;
  @ApiPropertyOptional() license_expiry: Date | null;
  @ApiPropertyOptional() license_state: string | null;
  @ApiPropertyOptional() license_country: string | null;
  @ApiPropertyOptional() address_line_one: string | null;
  @ApiPropertyOptional() address_line_two: string | null;
  @ApiPropertyOptional() address_suburb: string | null;
  @ApiPropertyOptional() address_state: string | null;
  @ApiPropertyOptional() address_post_code: string | null;
  @ApiPropertyOptional() address_country: string | null;
  @ApiPropertyOptional() emergency_name: string | null;
  @ApiPropertyOptional() emergency_phone: string | null;
  @ApiPropertyOptional() emergency_relation: string | null;
  @ApiPropertyOptional() business_name: string | null;
  @ApiPropertyOptional() business_abn: string | null;
  @ApiPropertyOptional() card_last_four: string | null;
  @ApiPropertyOptional() card_expiry_month: number | null;
  @ApiPropertyOptional() card_expiry_year: number | null;
  @ApiProperty() created_at: Date;
}
